#!/usr/bin/ruby
require 'parallel'
require 'fileutils'
require 'colorize'

logo = <<-'EOF'
--       )                       )                       
--    ( /(                    ( /(                       
--    )\())   )    (          )\())    )       )         
--  |((_)\ ( /(   ))\  (     ((_)\    (     ( /(  `  )   
--  |_ ((_))(_)) /((_) )\ )   _((_)   )\  ' )(_)) /(/(   
--  | |/ /((_)_ (_))  _(_/(  | \| | _((_)) ((_)_ ((_)_\  
--    ' < / _` |/ -_)| ' \)) | .` || '  \()/ _` || '_ \) 
--   _|\_\\__,_|\___||_||_|  |_|\_||_|_|_| \__,_|| .__/  
--                                               |_|     
--
EOF

def puts(string)
  current_time = Time.now.strftime('%a, %d %b %Y %H:%M:%S')
  super("[#{current_time}] ".yellow + "( #{string} )")
end

PWD = Dir.pwd

print logo.light_red
puts "Results will be saved to: #{PWD}"
puts 'Give me list of IP addresses: '
targets = STDIN.read.split("\n")

if targets.empty?
  puts "No targets given, exiting"
  return
end
puts "Selected targets: #{targets.join(', ')}"

targets.each do |target|
  target_nmap_dir = "#{PWD}/#{target}/nmap"

  puts "Initializing #{target} nmap results directory"
  FileUtils.mkdir_p(target_nmap_dir)
end

Parallel.each(targets, in_threads: 5) do |target|
  target_nmap_dir = "#{PWD}/#{target}/nmap"

  puts "Top 1000 TCP port discovery is in progress for: #{target}"
  `nmap -Pn -sT --top-ports 1000 -oA #{target_nmap_dir}/tcptop1000 #{target}`

  puts "Top 1000 TCP port discovery has finished for: #{target}".light_red

  puts "Default service version discovery is in progress for: #{target}"
  `nmap -Pn -sC -sV -oA #{target_nmap_dir}/versions #{target}`

  puts "Default service version discovery has finished for: #{target}".light_red

  puts "Full TCP port discovery is in progress for: #{target}"
  `nmap -Pn -p- -sT -oA #{target_nmap_dir}/full-tcp #{target}`

  puts "Full TCP port discovery has finished for: #{target}".light_red

  puts "OS discovery is in progress for: #{target}"
  `nmap -Pn -O -oA #{target_nmap_dir}/os #{target}`

  puts "OS discovery is has finished for: #{target}".light_red

  puts "Aggressive discovery is in progress for: #{target}"
  `nmap -Pn -A -oA #{target_nmap_dir}/aggressive #{target}`

  puts "Aggressive discovery has finished for: #{target}".light_red

  puts "Top 1000 UDP port discovery is in progress for: #{target}"
  `nmap -Pn -sU --top-ports 1000 -oA #{target_nmap_dir}/udptop1000 #{target}`

  puts "Top 1000 UDP port discovery has finished for: #{target}".light_red
end
